# -*- coding: utf-8 -*-
"""xgboost_tuning

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19PNv2WVKkQF2P5TXiQyC-TfY_j5BBHjg
"""

# pre optimized model, RMSLE = 0.18603804365839996
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_log_error
from xgboost import XGBRegressor

data = pd.read_csv(r"train_processed.csv", on_bad_lines='skip')#r"tmdb-box-office-data/train_processed.csv")

y = data["revenue_log"]

X = data.drop(columns=["revenue_log", "id", "revenue"])
X = X.select_dtypes(include=["number", "bool"])

print("Number of features used:", X.shape[1])

X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42)

model = XGBRegressor(
    n_estimators=300,
    learning_rate=0.05,
    max_depth=6,
    subsample=0.8,
    colsample_bytree=0.8,
    objective="reg:squarederror",
    tree_method="hist"
)

model.fit(X_train, y_train)

y_pred = model.predict(X_val)
base_rmsle = np.sqrt(mean_squared_log_error(y_val, y_pred))
print("XGBoost RMSLE:", base_rmsle)

!pip install optuna

# hyperparameter optimization
import optuna
import numpy as np
import xgboost as xgb
from sklearn.metrics import mean_squared_log_error

# Convert to DMatrix
dtrain = xgb.DMatrix(X_train, label=y_train)
dval = xgb.DMatrix(X_val, label=y_val)

n_estimators_options = 500

def objective(trial):

    params = {
        "objective": "reg:squarederror",
        "eta": trial.suggest_float("learning_rate", 0.01, 0.3),
        "max_depth": trial.suggest_int("max_depth", 3, 10),
        "subsample": trial.suggest_float("subsample", 0.5, 1.0),
        "colsample_bytree": trial.suggest_float("colsample_bytree", 0.5, 1.0),
        "eval_metric": "rmse",
        "tree_method": "hist"
    }

    model = xgb.train(
        params=params,
        dtrain=dtrain,
        num_boost_round=500,
        evals=[(dval, "val")],
        early_stopping_rounds=50,
        verbose_eval=False
    )

    y_pred = model.predict(dval)
    score = np.sqrt(mean_squared_log_error(y_val, y_pred))
    return score

best_params_with_n = []
best_scores_with_n = []
ns = np.arange(100, 500, 50)
for n in ns:
  print("num_estimators:", n)
  n_estimators_options = n
  study = optuna.create_study(direction="minimize")
  study.optimize(objective, n_trials=50)

  print("Best score:", study.best_value)
  print("Best parameters:", study.best_params)

  best_scores_with_n.append(study.best_value)
  best_params_with_n.append(study.best_params)

best_idx = best_scores_with_n.index(min(best_scores_with_n))
print("Best score with n:", min(best_scores_with_n))
print("Best parameters with n:", best_params_with_n[best_idx])
print("Best num_estimators:", ns[best_idx])

# Post optimization model, RMSLE =
model = XGBRegressor(
    n_estimators=200,
    learning_rate=0.1,
    max_depth=8,
    subsample=0.991,
    colsample_bytree=0.738,
    objective="reg:squarederror",
    tree_method="hist"
)

model.fit(X_train, y_train)

y_pred = model.predict(X_val)
optimized_rmsle = np.sqrt(mean_squared_log_error(y_val, y_pred))
print("XGBoost RMSLE:", optimized_rmsle)
print("Improvement:", base_rmsle-optimized_rmsle)